#ifndef _SERVER_CERTIFICATE
#define _SERVER_CERTIFICATE

// constexpr char SERVER_CERTIFICATE[] = "-----BEGIN CERTIFICATE-----\n"
//                                       "MIIF7jCCBNagAwIBAgISA4rCJCX4M9EFMRMfh+jzxDlMMA0GCSqGSIb3DQEBCwUA\n"
//                                       "MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD\n"
//                                       "EwJSMzAeFw0yNDAyMTAxNDAwMThaFw0yNDA1MTAxNDAwMTdaMBsxGTAXBgNVBAMM\n"
//                                       "ECoudXAucmFpbHdheS5hcHAwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoIC\n"
//                                       "AQCUhN0f/gYov1pLhsQMQXQNcpLMPsTs0O7B8ZNuBFfp96LfoEm4a2sgt53OK1rX\n"
//                                       "Hbgf9OC6JPt1tFHo2cDnlcl4NOA79qlR1QJxQ9eIOcFs2UmUlGZoSijuyDo7JxDE\n"
//                                       "r8436iOPImB3+R/hygwsy5Fs0Kxtrveisf0knKxJdb/yL81VqEIs0fVf5h1FsEQc\n"
//                                       "HsqgqqxJJGqEvCkBRmOJ+0Kgz9pk4v0x6JEBaXi9GCB4Hc5cncETAiv4WjXQ3hyf\n"
//                                       "MNHIOkhVSJtPvvi9cxQk9uEmOzy83zVmnwckwbdN0lmfJFbZG69wp+L1b8z3ZGQB\n"
//                                       "CNNhVe1nHP+RuKLLvQcqKUr8PYy1nhEYCoHuIfoyPCvC5eDni+W0OTK76PyGxJ3/\n"
//                                       "gOQ23397+bD4rIj+becjM6UHMCzP8qUOc6LsB/iySdgPay3UXPcNYPieunBLlxZ0\n"
//                                       "lLsMf5GkXhP2V8vKwnZk3DreulKA6j1sKmDEOV1m6GP1q5L9TqJmTMUvMSR0pxf7\n"
//                                       "fIQqtDuFwgFxVKYgKbJOqqIdK3kzXSsaxYl7+L7lJ99EIsAACOvkjkG84cZwnsDS\n"
//                                       "M+tF1Qt788zxYZ1mSSh7D17cD93mJb2iyxgU6Zkdene0DzV8mO7ruaWRN6jMybJe\n"
//                                       "KGdUMT7dwAhKDrYYrdx/YnqOvF8LF3/ENY1iyEqjzvv5ZQIDAQABo4ICEzCCAg8w\n"
//                                       "DgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAM\n"
//                                       "BgNVHRMBAf8EAjAAMB0GA1UdDgQWBBQNQ6kn2NVkkIddElnsG1XvA9veZzAfBgNV\n"
//                                       "HSMEGDAWgBQULrMXt1hWy65QCUDmH6+dixTCxjBVBggrBgEFBQcBAQRJMEcwIQYI\n"
//                                       "KwYBBQUHMAGGFWh0dHA6Ly9yMy5vLmxlbmNyLm9yZzAiBggrBgEFBQcwAoYWaHR0\n"
//                                       "cDovL3IzLmkubGVuY3Iub3JnLzAbBgNVHREEFDASghAqLnVwLnJhaWx3YXkuYXBw\n"
//                                       "MBMGA1UdIAQMMAowCAYGZ4EMAQIBMIIBBQYKKwYBBAHWeQIEAgSB9gSB8wDxAHcA\n"
//                                       "SLDja9qmRzQP5WoC+p0w6xxSActW3SyB2bu/qznYhHMAAAGNk4iWbAAABAMASDBG\n"
//                                       "AiEA/eBNLv7rWBend+dJxD+RSB3DoKNmc8WKP+bdz9br2CoCIQDX7ny+dIYWHbuz\n"
//                                       "AgzYtIXqoZJxVNQYlIjETgV3DdlvlQB2AHb/iD8KtvuVUcJhzPWHujS0pM27Kdxo\n"
//                                       "Qgqf5mdMWjp0AAABjZOIlsAAAAQDAEcwRQIhAMkqVATYGMkDpFf9oU2OX5FCqKFq\n"
//                                       "XlC0ZGBpCpYbNkWdAiAfVJQiavHHUij38HI321iiwtwPERGFKQD5f921ty14pzAN\n"
//                                       "BgkqhkiG9w0BAQsFAAOCAQEAkaWJd2lHrVKmt3IipzmeNKGQqHCXFjRAUpG/19bk\n"
//                                       "4obB671bLvOZw4EkNqK3nwLtI60LImWG13dqaDgJwCRnSPVOskoWmdhDwFa8pAlv\n"
//                                       "9pnGYHUMueRp5NE8KKlwTz9sry3NipheBe2yKGr5ezi3mc0c/s80VNG860OvP2Xd\n"
//                                       "TOrMOmOwCEx9StcIXc3VfPi4EHEt+gHHJduGM8t6AtPcz2yrMwWkypvtyh5Ym8a5\n"
//                                       "mw1P+t4hD1yoN1e18b0FeKP+CF0R+nmUGUEfrM4ofeP0R97bY0eF2y/+79Ym8OrY\n"
//                                       "2EF8LmA4NY83u6RTt0J4/xYhTp2nAS2KsJJHSO10BZW26A==\n"
//                                       "-----END CERTIFICATE-----";

// Last certificate in chain PEM:
constexpr char SERVER_CERTIFICATE[] = "-----BEGIN CERTIFICATE-----\n"
                                      "MIIFazCCA1OgAwIBAgIRAIIQz7DSQONZRGPgu2OCiwAwDQYJKoZIhvcNAQELBQAw\n"
                                      "TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh\n"
                                      "cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMTUwNjA0MTEwNDM4\n"
                                      "WhcNMzUwNjA0MTEwNDM4WjBPMQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJu\n"
                                      "ZXQgU2VjdXJpdHkgUmVzZWFyY2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBY\n"
                                      "MTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAK3oJHP0FDfzm54rVygc\n"
                                      "h77ct984kIxuPOZXoHj3dcKi/vVqbvYATyjb3miGbESTtrFj/RQSa78f0uoxmyF+\n"
                                      "0TM8ukj13Xnfs7j/EvEhmkvBioZxaUpmZmyPfjxwv60pIgbz5MDmgK7iS4+3mX6U\n"
                                      "A5/TR5d8mUgjU+g4rk8Kb4Mu0UlXjIB0ttov0DiNewNwIRt18jA8+o+u3dpjq+sW\n"
                                      "T8KOEUt+zwvo/7V3LvSye0rgTBIlDHCNAymg4VMk7BPZ7hm/ELNKjD+Jo2FR3qyH\n"
                                      "B5T0Y3HsLuJvW5iB4YlcNHlsdu87kGJ55tukmi8mxdAQ4Q7e2RCOFvu396j3x+UC\n"
                                      "B5iPNgiV5+I3lg02dZ77DnKxHZu8A/lJBdiB3QW0KtZB6awBdpUKD9jf1b0SHzUv\n"
                                      "KBds0pjBqAlkd25HN7rOrFleaJ1/ctaJxQZBKT5ZPt0m9STJEadao0xAH0ahmbWn\n"
                                      "OlFuhjuefXKnEgV4We0+UXgVCwOPjdAvBbI+e0ocS3MFEvzG6uBQE3xDk3SzynTn\n"
                                      "jh8BCNAw1FtxNrQHusEwMFxIt4I7mKZ9YIqioymCzLq9gwQbooMDQaHWBfEbwrbw\n"
                                      "qHyGO0aoSCqI3Haadr8faqU9GY/rOPNk3sgrDQoo//fb4hVC1CLQJ13hef4Y53CI\n"
                                      "rU7m2Ys6xt0nUW7/vGT1M0NPAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNV\n"
                                      "HRMBAf8EBTADAQH/MB0GA1UdDgQWBBR5tFnme7bl5AFzgAiIyBpY9umbbjANBgkq\n"
                                      "hkiG9w0BAQsFAAOCAgEAVR9YqbyyqFDQDLHYGmkgJykIrGF1XIpu+ILlaS/V9lZL\n"
                                      "ubhzEFnTIZd+50xx+7LSYK05qAvqFyFWhfFQDlnrzuBZ6brJFe+GnY+EgPbk6ZGQ\n"
                                      "3BebYhtF8GaV0nxvwuo77x/Py9auJ/GpsMiu/X1+mvoiBOv/2X/qkSsisRcOj/KK\n"
                                      "NFtY2PwByVS5uCbMiogziUwthDyC3+6WVwW6LLv3xLfHTjuCvjHIInNzktHCgKQ5\n"
                                      "ORAzI4JMPJ+GslWYHb4phowim57iaztXOoJwTdwJx4nLCgdNbOhdjsnvzqvHu7Ur\n"
                                      "TkXWStAmzOVyyghqpZXjFaH3pO3JLF+l+/+sKAIuvtd7u+Nxe5AW0wdeRlN8NwdC\n"
                                      "jNPElpzVmbUq4JUagEiuTDkHzsxHpFKVK7q4+63SM1N95R1NbdWhscdCb+ZAJzVc\n"
                                      "oyi3B43njTOQ5yOf+1CceWxG1bQVs5ZufpsMljq4Ui0/1lvh+wjChP4kqKOJ2qxq\n"
                                      "4RgqsahDYVvTH9w7jXbyLeiNdd8XM2w9U/t7y0Ff/9yi0GE44Za4rF2LN9d11TPA\n"
                                      "mRGunUHBcnWEvgJBQl9nJEiU0Zsnvgc/ubhPgXRR4Xq37Z0j4r7g1SgEEzwxA57d\n"
                                      "emyPxgcYxn/eR44/KJ4EBs+lVDR3veyJm+kXQ99b21/+jh5Xos1AnX5iItreGCc=\n"
                                      "-----END CERTIFICATE-----";

#endif